dist: focal
language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
branches:
  only:
  - develop
  - uat
  - prod
deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id:
    develop: AKIAWKBC6B4EVCA652NR
    uat: AKIAWKBC6B4EVCA652NR
    prod: AKIAWKBC6B4EVCA652NR
  secret_access_key:
    develop:
      secure: "DrJhkxF5tRWkcXykwvrPKVcxjt6mmlSih/6BJ6CagfRKxg4wuCpa9J99Rbki1WbV5XWuDp/TJ257hBwGAAjUz7aFRQE0vUHiOZNkL4Cz2DUnqWvWzmVEtG3rNDX2/ncw0Iml4afOh1OkrMRit2ua3xCsNQHs+wPFYyY8xs1F8vOWgLGuTAhXzq3Y4QhuRKd93qrGbySmC3s9pH69Dhwb7usDy9jfudfxCNT2vrjH2WbG65f88f06sphM592CwfzNlMHhPuWsvFMSS7GkLRVPbbMytbhkJAb2GkYWnwv2M2tFJ+WeclW50/Cet1nG69kU/SxmS7PUWpPbHXTJ2yt7hc+8juDabvxxzA9Hf5V6ADUeWcsx59l/7PKfQEiUlgkVEXUm3Ct5ZMKcknh+XkdBmROYS1CwHBYol4veUS+OIfQkkDo5TVhr5aUr6HfjDL+jZbmitxijhpGfMShVWSDyMLXKsp12hhFfFz4E3XC3aza0oTJ10ZqmrluDkuYmCVyP0e6zNL8kf+CExwghxs312QRC3LFnHnPdz/L711YQXhSxvLnVr2L5WEVRxTYD60uvFKnH8HGhQfYOIducEvnSRhtlK8c1aUnTs9GAWgPnXHpiQEwjAk85HqzoaPgY5pNsCPdYPxLBrWKpNOwbDteEm1Ir9vvlBJooCj5Fz+3D4Us="
    uat:
      secure: "DrJhkxF5tRWkcXykwvrPKVcxjt6mmlSih/6BJ6CagfRKxg4wuCpa9J99Rbki1WbV5XWuDp/TJ257hBwGAAjUz7aFRQE0vUHiOZNkL4Cz2DUnqWvWzmVEtG3rNDX2/ncw0Iml4afOh1OkrMRit2ua3xCsNQHs+wPFYyY8xs1F8vOWgLGuTAhXzq3Y4QhuRKd93qrGbySmC3s9pH69Dhwb7usDy9jfudfxCNT2vrjH2WbG65f88f06sphM592CwfzNlMHhPuWsvFMSS7GkLRVPbbMytbhkJAb2GkYWnwv2M2tFJ+WeclW50/Cet1nG69kU/SxmS7PUWpPbHXTJ2yt7hc+8juDabvxxzA9Hf5V6ADUeWcsx59l/7PKfQEiUlgkVEXUm3Ct5ZMKcknh+XkdBmROYS1CwHBYol4veUS+OIfQkkDo5TVhr5aUr6HfjDL+jZbmitxijhpGfMShVWSDyMLXKsp12hhFfFz4E3XC3aza0oTJ10ZqmrluDkuYmCVyP0e6zNL8kf+CExwghxs312QRC3LFnHnPdz/L711YQXhSxvLnVr2L5WEVRxTYD60uvFKnH8HGhQfYOIducEvnSRhtlK8c1aUnTs9GAWgPnXHpiQEwjAk85HqzoaPgY5pNsCPdYPxLBrWKpNOwbDteEm1Ir9vvlBJooCj5Fz+3D4Us="
    prod:
      secure: "DrJhkxF5tRWkcXykwvrPKVcxjt6mmlSih/6BJ6CagfRKxg4wuCpa9J99Rbki1WbV5XWuDp/TJ257hBwGAAjUz7aFRQE0vUHiOZNkL4Cz2DUnqWvWzmVEtG3rNDX2/ncw0Iml4afOh1OkrMRit2ua3xCsNQHs+wPFYyY8xs1F8vOWgLGuTAhXzq3Y4QhuRKd93qrGbySmC3s9pH69Dhwb7usDy9jfudfxCNT2vrjH2WbG65f88f06sphM592CwfzNlMHhPuWsvFMSS7GkLRVPbbMytbhkJAb2GkYWnwv2M2tFJ+WeclW50/Cet1nG69kU/SxmS7PUWpPbHXTJ2yt7hc+8juDabvxxzA9Hf5V6ADUeWcsx59l/7PKfQEiUlgkVEXUm3Ct5ZMKcknh+XkdBmROYS1CwHBYol4veUS+OIfQkkDo5TVhr5aUr6HfjDL+jZbmitxijhpGfMShVWSDyMLXKsp12hhFfFz4E3XC3aza0oTJ10ZqmrluDkuYmCVyP0e6zNL8kf+CExwghxs312QRC3LFnHnPdz/L711YQXhSxvLnVr2L5WEVRxTYD60uvFKnH8HGhQfYOIducEvnSRhtlK8c1aUnTs9GAWgPnXHpiQEwjAk85HqzoaPgY5pNsCPdYPxLBrWKpNOwbDteEm1Ir9vvlBJooCj5Fz+3D4Us="
  region: us-east-1
  app: BridgeServer2-application
  env: bridgeserver2-$TRAVIS_BRANCH
  bucket:
    develop: org-gvbridge-bridgeserver2-deployment-devdevelop
    uat: org-gvbridge-bridgeserver2-deployment-devstaging
    prod: org-gvbridge-bridgeserver2-deployment-prod
  zip-file: target/BridgeServer2-2.1-SNAPSHOT.war
  on:
    all_branches: true
