dist: focal
language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
branches:
  only:
  - develop
  - uat
  - prod
deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id:
    develop: AKIAJQOD25TNB4GR4LFQ
    uat: AKIAJQOD25TNB4GR4LFQ
    prod: AKIAZOKKB636GOXML5BE
  secret_access_key:
    develop:
      secure: "yTu9XPDJvubWG3iwx1o2rwMHetHdQ07jIwXrYmFyHQmOdU+AVWMKujBi8JUQb/T9nxcQirR05//aeeZ4ZQ46RBT1LSmYNTCCDxHZwyxh3cEl3X7v+CCgJUQJgun+gubTYGDYXBwT9uOuqhZLmqzATyorKrGS1t6QXJs5QVQ7JpcgbCRPT10t2hYfRBV81b+5JtWVBcJj/B7qLfa61IYehlqnvfNDVZdn4TEJI2D+1FYndn/uTnrWRfe6LuWkB95hwzVw81HN8AxZxPFS61PDJc5Sm2bt/vNgnYyY4Eqm1pqZxSg3x6GlcNe0LuhtOq8eI/j2MBgMOesZsXDwPNf2NCdkE/703VHSODOOPUDfHkgkiVxXmyqA4+LtEmNXhDpm0Pn969FXdSpD3LSvDxl9agXHx79kwo1AbhGiZPq48zliPL7QnWxKkuPdC7wSi3d4J73+sjFll4AGlOcz0Pp+BVvowtUG1JkWnFIMlFbKcP3PP3KTpNmVDvieJZXy1bYK15ZTtrPSMZlruRyeRPqMFD13JcOdy4SSbXfF+3xIILYRRW7sabCW5Ccby4Q1H4q2WEQs/+5uYbsqrjW4XcI9ZOtbGbR5swDUivttY+K5G+6P+tZVVQRCvhhQ11i2VqWn21F+ob+onIu7SQnw2/gVaNFvAT6F8vALSXNQjfwfmwY="
    uat:
      secure: "yTu9XPDJvubWG3iwx1o2rwMHetHdQ07jIwXrYmFyHQmOdU+AVWMKujBi8JUQb/T9nxcQirR05//aeeZ4ZQ46RBT1LSmYNTCCDxHZwyxh3cEl3X7v+CCgJUQJgun+gubTYGDYXBwT9uOuqhZLmqzATyorKrGS1t6QXJs5QVQ7JpcgbCRPT10t2hYfRBV81b+5JtWVBcJj/B7qLfa61IYehlqnvfNDVZdn4TEJI2D+1FYndn/uTnrWRfe6LuWkB95hwzVw81HN8AxZxPFS61PDJc5Sm2bt/vNgnYyY4Eqm1pqZxSg3x6GlcNe0LuhtOq8eI/j2MBgMOesZsXDwPNf2NCdkE/703VHSODOOPUDfHkgkiVxXmyqA4+LtEmNXhDpm0Pn969FXdSpD3LSvDxl9agXHx79kwo1AbhGiZPq48zliPL7QnWxKkuPdC7wSi3d4J73+sjFll4AGlOcz0Pp+BVvowtUG1JkWnFIMlFbKcP3PP3KTpNmVDvieJZXy1bYK15ZTtrPSMZlruRyeRPqMFD13JcOdy4SSbXfF+3xIILYRRW7sabCW5Ccby4Q1H4q2WEQs/+5uYbsqrjW4XcI9ZOtbGbR5swDUivttY+K5G+6P+tZVVQRCvhhQ11i2VqWn21F+ob+onIu7SQnw2/gVaNFvAT6F8vALSXNQjfwfmwY="
    prod:
      secure: "S7H7ypa+pbxRCNacWF1yDjbMnu4ejive96epWjXlp3RgQVysUqctXRGvpuXIxopYtU/WHsVLXy2WG1u7WTveCUmP21TNB5R+V9LK7oZO0V16K76zaipopoa2VsxBnxvtPR+iaP2dMwkAjdYIgb2WxhsatnbOBuKaogiOiAbq19mMuRzDm/8Jeop2wSLw1sn+N7bsZLey7b66NF7PirrW0Q9VetYJnN2//sQbj0QH3SaZmNDlqN4llE2B7LIXO09ZKLcaJpVs/28bY/VmG+H3PsCaSnhFJ7Edk2P2fLLe6xKit9Dc+FaKbuiQoznMcFii84Od+mF3S9UKR1kKK/qDj4lRr2P6/Hu7HYA+MmGJCwV1pTPXowuYyqnc1SgftzrYhpRtNQkr2rqsyDIQsjJYze1Ez+ZkuD9HcHcb1300aDW7u2nqNUV5rGMZMqCCxeYP4E84JfILrv830ix/fqMq7Jphc4q+a6R2kCuqGjqBdqpMYcH8lLLvTOSVDnw7xMRpm22H5KskDw3MNWE6t9EVzzubWzEC9PpjvMORbPArkJbvHrvEyZMWWjlsqCK1DvPwhM2Brd82Kg2vCZIFPnKS7jWGiBMKVbzcZnIWoXKiWzNQGX8XHEQUs4wKz6SshdbrMfU7J7XUQDD+ChRUJxksi3gfWgX29TzresxM="
  region: us-east-1
  app: BridgeServer2-application
  env: bridgeserver2-$TRAVIS_BRANCH
  bucket:
    develop: org-sagebridge-bridgeserver2-deployment-devdevelop
    uat: org-sagebridge-bridgeserver2-deployment-devstaging
    prod: org-sagebridge-bridgeserver2-deployment-prod
  zip-file: target/BridgeServer2-2.1-SNAPSHOT.war
  on:
    all_branches: true
